### ISSUE TITLE
Interest in contributing

### ISSUE THREAD

**Issue by billiegoose** [ipfs/ipfs-npm#1]
Is this a project to provide an npm alternative for Node that uses IPFS for the registry instead of npmjs.org? If so I volunteer to help! I have three years of Node.js experience, have written or maintain a number of modules on https://www.npmjs.com/~wmhilton and while I'm new to IPFS I strongly believe in decentralized alternatives to the internet such as mesh networks! 

I actually stumbled across IPFS about a month ago, but yesterday's left-pad incident has motivated me to get off my butt and do something.

**Comment by hackergrrl** [comment]
Hey, welcome! I can give you a few pointers in the right direction on this:
1. https://github.com/diasdavid/registry-mirror is an npm registry that uses IPFS as a backend. It's worth talking to @diasdavid about this. (I hear @VictorBjelkholm may also have thoughts on this subject.)
2. https://github.com/whyrusleeping/gx is a generic distributed package manager with git-like hooks for plugging in new language/ecosystem support. There's https://github.com/whyrusleeping/gx-go for Go, but we're lacking a gx-node implementation. Talk to @whyrusleeping or even myself about this.

**Comment by jbenet** [comment]
Welcome! ^ what @noffle said. make sure to talk to @diasdavid about registry-mirror. we've lots of thoughts in that space, spread out across issues. yes the time is now for fixing all of this! 

find us on IRC too. #ipfs on freenode if you want to discuss realtime. and on mondays we have sync hangouts.

we've been building towards this for a while now. and we've finally gotten ipfs to where it needs to be, and the first good experiments (registry-mirror and gx) going. lots more to come \o/. for history:
- https://github.com/jbenet/random-ideas/issues/19 <--- still has ideas that we need to think more about with registry-mirror and gx (right now they download, instead of relying on mounting because FUSE is really painful)
- https://github.com/jbenet/random-ideas/issues/27 <--- im really interested in this, but it's likely way out of scope for now. maybe in a year or two.

**Comment by daviddias** [comment]
Hi @wmhilton, great to hear from you, welcome! :D 

As @jbenet and @noffle mentioned, we've started that endeavour to enable the npm cli to use IPFS as a transport to fetch modules from the IPFS network. 

What this means is that: if the module is available on the network, you can find it, even if you are disconnected from the 'Internet', you just need to be connected somehow (think LAN on a train/plane/office/etc) to find the other machine locally that has the module you need. 

I've delivered a talk at Node.js Interactive showing its capabilities - https://www.youtube.com/watch?v=-S-Tc7Gl8FM

Right now we are working towards getting registry-mirror UX/DX amazing, in conjunction with the release of IPFS 0.4.0 that introduced the underlying "Files API" that enabled it to work. 

If you would like to talk (irc, chat, email, through this issue) about the rational of registry-mirror and how you can help, let me know, would love to get your participation.

registry-mirror - https://github.com/diasdavid/registry-mirror

**Comment by billiegoose** [comment]
Sounds awesome! What timezone are you guys operating in? I'm booked today but maybe tomorrow I can get on IRC and discuss stuff. My goal is to get a mirror up this weekend. I can be a beta tester or whatever, and work on the UX!

**Comment by billiegoose** [comment]
Sorry I haven't followed up - my personal life suddenly got even busier which I didn't think was possible! I'll be back to spend time on this project again in a week or two

**Comment by billiegoose** [comment]
The likelihood that I'll have time to contribute continue to dwindle. Closing this issue because I'm trying to clean up my github backlog.
